In [10]:
import numpy as np

np.random.seed(42)

In [11]:
A = np.random.randint(1, 11, size=(4, 3))

print("Matrix A:")
print(A)
print("Shape of A:", A.shape)

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape of A: (4, 3)


In [12]:
B = np.random.randint(1,11, size=(3,5))

print("Matrix B:")
print(B)
print("Shape of B:", B.shape)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape of B: (3, 5)


In [13]:
assert A.shape[1] == B.shape[0], "Inner dimensions do not match"

print("Dimension validation successful.")
print("A columns:", A.shape[1])
print("B rows:", B.shape[0])

Dimension validation successful.
A columns: 3
B rows: 3


In [14]:
C = A @ B

print("Matrix C = A @ B:")
print(C)
print("Shape of C:", C.shape)

assert C.shape == (4, 5)


Matrix C = A @ B:
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape of C: (4, 5)


In [15]:
total_sum = np.sum(C)

print("Total sum of elements in C:", total_sum)


Total sum of elements in C: 2188


In [16]:
row_sums = np.sum(C, axis=1)

print("Row-wise sums:")
print(row_sums)


Row-wise sums:
[544 634 514 496]


In [17]:
column_sums = np.sum(C, axis=0)

print("Column-wise sums:")
print(column_sums)


Column-wise sums:
[676 396 470 244 402]
